name: Verify Python Format

on: [push]

jobs:
  verify_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install pep8
        run: |
          python -m pip install --upgrade pep8
      - name: Verify Python Format
        run: |
          # Find all Python files in the repository
          find . -name "*.py" | xargs pep8 --ignore=E402